### ISSUE TITLE
uninitialized constant Retrospec::Puppet::Generators::BaseGenerator (NameError)

### ISSUE THREAD

**Issue by Poil** [logicminds/retrospec#6]
Hi,

I'm trying latest version of (puppet-)retrospec but I have this error :
```
/var/lib/gems/2.3.0/gems/puppet-retrospec-1.6.0/lib/retrospec/plugins/v1/plugin/generators/module_data_generator.rb:7:in `<module:Generators>': uninitialized constant Retrospec::Puppet::Generators::BaseGenerator (NameError)
```

All is working fine with retrospec (0.5.1) and puppet-retrospec (1.3.0)

I've tried in a rvm and rbenv environment with Ruby 2.0, 2.1, 2.2 ... I'm out of idea, do you have one ?

Best regards,

**Comment by logicminds** [comment]
Try `gem update retrospec`.  The latest version is 0.6.2.

**Comment by logicminds** [comment]
Also please open issue here: github.com/nwops/puppet-retrospec

**Comment by logicminds** [comment]
I have never needed this but maybe something changed recently that now requires this:

https://github.com/nwops/puppet-retrospec/commit/481d34866c8c9ee0aece7a9deb699da82218d3a1

If you are able to patch your gem with this requirement and test out I can push a new release.

**Comment by xalimar** [comment]
I ran into the same error, and the patch you have in 481d348 fixed the problem for me.  (I also needed to gem install facter in a clean rvm environment with nothing other than gem install puppet-retrospec ran in it)
